(library
 (flags
  (:standard
   -open
   Tsync_log
   -open
   Tsync_retry
   -open
   Tsync_bigstring
   -open
   Tsync_local_io
   -open
   Tsync_field_spec
   -open
   Tsync_metrics
   -open
   Tsync_io_lwt
   -open
   Tsync_logical_key))
 (name tsync_backend_register)
 (public_name tsync-libs.backend_register)
 (libraries
  tsync_logical_key
  tsync_retry
  tsync_field_spec
  tsync_metrics
  tsync_bigstring
  tsync_local_io
  tsync_io_lwt
  tsync_log
  lwt
  lwt.unix))
