(library
 (flags
  (:standard
   -open
   Tsync_log
   -open
   Tsync_chunk
   -open
   Tsync_local_io
   -open
   Tsync_field_spec
   -open
   Tsync_metrics
   -open
   Tsync_lwt_unix))
 (name tsync_backend_register)
 (public_name tsync-libs.backend_register)
 (libraries
  tsync_field_spec
  tsync_metrics
  tsync_chunk
  tsync_local_io
  tsync_lwt_unix
  tsync_log
  lwt
  lwt.unix))
