(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_chunks
   -open
   Tsync_remote
   -open
   Tsync_journal
   -open
   Tsync_sync
   -open
   Tsync_content
   -open
   Tsync_store
   -open
   Tsync_naming
   -open
   Tsync_log
   -open
   Tsync_metrics
   -open
   Tsync_local_io
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_ipc
   -open
   Tsync_lwt_unix
   -open
   Tsync_conf))
 (name tsync_diagnostics)
 (public_name tsync-libs.diagnostics)
 (libraries
  tsync_logical_key
  tsync_chunks
  tsync_remote
  tsync_journal
  tsync_sync
  tsync_content
  tsync_store
  tsync_naming
  tsync_local_io
  tsync_conf
  tsync_lwt_unix
  tsync_bigstring
  tsync_backend_register
  tsync_ipc
  tsync_metrics
  tsync_log
  yojson
  unix
  lwt
  lwt.unix))
