(executable
 (flags
  (:standard
   -open
   Tsync_chunks
   -open
   Tsync_xxhash
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_backend
   -open
   Tsync_naming
   -open
   Tsync_conf
   -open
   Tsync_test_harness))
 (name conformance)
 (libraries
  tsync_chunks
  tsync_xxhash
  tsync_bigstring
  tsync_conf
  tsync_backend_register
  tsync_backend
  tsync_naming
  tsync_test_harness
  bigstringaf
  lwt
  lwt.unix
  unix))
