(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_backend
   -open
   Tsync_conf
   -open
   Tsync_test_harness))
 (name conformance)
 (libraries
  tsync-libs.core
  tsync_backend_api
  tsync_core
  tsync_conf
  tsync_backend_lwt
  tsync_backend
  tsync_test_harness
  bigstringaf
  lwt
  lwt.unix
  unix))
