(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_retry
   -open
   Tsync_chunk_integrity
   -open
   Tsync_field_spec
   -open
   Tsync_log
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_io
   -open
   Tsync_retry))
 (name tsync_s3_backend)
 (optional)
 (libraries
  aws-s3
  tsync-libs.logical_key
  tsync_retry
  tsync_io
  tsync_chunk_integrity
  tsync-libs.field_spec
  tsync-libs.bigstring
  tsync-libs.backend_register
  tsync-libs.log))
