(library
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_chunk_integrity
   -open
   Tsync_backend_register
   -open
   Tsync_io))
 (name tsync_s3_backend)
 (optional)
 (libraries
  aws-s3
  tsync-libs.core
  tsync_core
  tsync_io
  tsync_chunk_integrity
  tsync-libs.backend_register))
