(library
 (flags
  (:standard
   -open
   Tsync_field_spec
   -open
   Tsync_log
   -open
   Tsync_backend_register))
 (name tsync_s3_backend)
 (private_modules s3_backend)
 (optional)
 (library_flags (-linkall))
 (libraries
  tsync_field_spectsync_backend_register
  tsync_log
  aws-s3-lwt
  lwt
  lwt.unix))
