(executable
 (name zip_test)
 (libraries tsync_zip))

(alias
 (name default)
 (deps zip_test.exe))

(rule
 (alias runtest)
 (target zip_test.output)
 (action
  (with-stdout-to
   zip_test.output
   (ignore-stderr
    (setenv
     TZ
     UTC
     (run ./zip_test.exe))))))

(rule
 (alias runtest)
 (action
  (diff zip_test.expected zip_test.output)))
