(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_naming
   -open
   Tsync_local_io
   -open
   Tsync_io_lwt
   -open
   Tsync_test_harness))
 (name folder_ids_test)
 (libraries
  tsync_logical_key
  tsync_test_harness
  tsync_naming
  tsync_io_lwt
  tsync_local_io
  lwt
  lwt.unix
  unix))
