(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_folder_ids
   -open
   Tsync_folder_ids_lwt
   -open
   Tsync_cache_layout
   -open
   Tsync_io_lwt
   -open
   Tsync_test_harness))
 (name folder_ids_test)
 (libraries
  tsync_logical_key
  tsync_test_harness
  tsync_folder_ids
  tsync_folder_ids_lwt
  tsync_cache_layout
  tsync_io_lwt
  lwt
  lwt.unix
  unix))
