(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_remote
   -open
   Tsync_manifest
   -open
   Tsync_chunks
   -open
   Tsync_test_harness
   -open
   Tsync_content
   -open
   Tsync_content_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf
   -open
   Tsync_local_backend))
 (name upload)
 (libraries
  lwt.unix
  lwt
  tsync_logical_key
  tsync_remote
  tsync_manifest
  tsync_chunks
  tsync_test_harness
  tsync_content
  tsync_content_lwt
  tsync_conf
  tsync_backend_register
  tsync_backend_lwt
  tsync_local_backend))
