(library
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_engine
   -open
   Tsync_diagnostics
   -open
   Tsync_conf
   -open
   Tsync_conf_lwt))
 (name tsync_frontend_register)
 (public_name tsync-libs.frontend_register)
 (libraries
  tsync_core
  tsync-libs.engine
  tsync_diagnostics
  tsync_conf
  tsync_conf_lwt
  unix
  lwt.unix))
