(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_bigstring
   -open
   Tsync_io_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_domain_store_lwt
   -open
   Tsync_test_harness))
 (name mirror_pools)
 (libraries
  tsync-libs.logical_key
  tsync_test_harness
  tsync_ops
  tsync_ops_lwt
  tsync_bigstring
  tsync_io_lwt
  tsync_backend_register
  tsync_backend_lwt
  tsync_conf_lwt
  tsync_local_backend_lwt
  tsync_domain_store_lwt
  lwt
  lwt.unix))
