(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_ops
   -open
   Tsync_bigstring
   -open
   Tsync_io_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend
   -open
   Tsync_domain_store
   -open
   Tsync_test_harness))
 (name mirror_pools)
 (libraries
  tsync-libs.logical_key
  tsync_test_harness
  tsync_ops
  tsync_bigstring
  tsync_io_lwt
  tsync_backend_register
  tsync_conf
  tsync_local_backend
  tsync_domain_store
  lwt
  lwt.unix
  unix))
