(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_layout
   -open
   Tsync_layout_lwt
   -open
   Tsync_file_store
   -open
   Tsync_test_harness
   -open
   Tsync_engine
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_store))
 (name presenting_domain)
 (libraries
  tsync_logical_key
  tsync_layout
  tsync_layout_lwt
  tsync_file_store
  tsync_test_harness
  tsync-libs.engine
  tsync-libs.store
  tsync-libs.conf
  tsync_backend_register
  tsync_backend_lwt
  tsync_conf_lwt
  tsync_local_backend_lwt
  yojson
  lwt
  lwt.unix))
