(executable
 (flags
  (:standard
   -open
   Tsync_store
   -open
   Tsync_test_harness
   -open
   Tsync_engine
   -open
   Tsync_naming
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend
   -open
   Tsync_store))
 (name presenting_domain)
 (libraries
  tsync_store
  tsync_test_harness
  tsync-libs.engine
  tsync-libs.naming
  tsync-libs.store
  tsync-libs.conf
  tsync_backend_register
  tsync_local_backend
  yojson
  lwt
  lwt.unix))
