(library
 (flags
  (:standard
   -open
   Tsync_frontend_register
   -open
   Tsync_sync
   -open
   Tsync_store
   -open
   Tsync_object
   -open
   Tsync_log
   -open
   Tsync_conf
   -open
   Tsync_backend_register
   -open
   Tsync_ipc_handler
   -open
   Tsync_work))
 (name tsync_engine)
 (libraries
  tsync_frontend_register
  tsync_sync
  tsync_store
  tsync_object
  tsync_backend_register
  tsync_conf
  tsync_ipc_handler
  tsync_log
  tsync_work
  lwt))
