(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_journal
   -open
   Tsync_conf
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_file_store
   -open
   Tsync_test_harness))
 (name cursor_debounce)
 (libraries
  tsync-libs.logical_key
  tsync_journal
  tsync_test_harness
  tsync_conf
  tsync_bigstring
  tsync_backend_register
  tsync_file_store
  tsync_local_backend
  lwt
  lwt.unix
  unix))
