(executable
 (name demand_paging)
 (libraries tsync_test_runner))

(alias
 (name default)
 (deps demand_paging.exe))

(rule
 (alias runtest)
 (target demand_paging.output)
 (action
  (with-stdout-to
   demand_paging.output
   (ignore-stderr
    (setenv
     TSYNC_CHUNK_SIZE
     8
     (run ./demand_paging.exe))))))

(rule
 (alias runtest)
 (action
  (diff demand_paging.expected demand_paging.output)))
