(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_diagnostics
   -open
   Tsync_test_harness))
 (name probe_deadline_test)
 (libraries
  tsync-libs.core
  tsync_test_harness
  tsync_backend_register
  tsync_backend_lwt
  tsync_local_backend_lwt
  tsync_diagnostics
  tsync_conf_lwt
  yojson
  lwt
  lwt.unix))
