(executable
 (name formats_test)
 (modules formats_test)
 (libraries tsync_core tsync_remote tsync_checkout tsync_sync yojson unix))

(rule
 (with-stdout-to
  formats_test.output
  (run ./formats_test.exe)))

(rule
 (alias runtest)
 (action
  (diff formats_test.expected formats_test.output)))

(executable
 (name two_clients_test)
 (modules two_clients_test)
 (libraries
  tsync_core
  tsync_store
  tsync_remote
  tsync_checkout
  tsync_sync
  unix))

(rule
 (with-stdout-to
  two_clients_test.output
  (run ./two_clients_test.exe)))

(rule
 (alias runtest)
 (action
  (diff two_clients_test.expected two_clients_test.output)))

(executable
 (name import_plan_test)
 (modules import_plan_test)
 (libraries tsync_core tsync_sync unix))

(rule
 (with-stdout-to
  import_plan_test.output
  (run ./import_plan_test.exe)))

(rule
 (alias runtest)
 (action
  (diff import_plan_test.expected import_plan_test.output)))

(executable
 (name import_test)
 (modules import_test)
 (libraries
  tsync_core
  tsync_store
  tsync_remote
  tsync_checkout
  tsync_sync
  unix))

(rule
 (with-stdout-to
  import_test.output
  (run ./import_test.exe)))

(rule
 (alias runtest)
 (action
  (diff import_test.expected import_test.output)))

(executable
 (name rsync_plan_test)
 (modules rsync_plan_test)
 (libraries tsync_core tsync_sync))

(rule
 (with-stdout-to
  rsync_plan_test.output
  (run ./rsync_plan_test.exe)))

(rule
 (alias runtest)
 (action
  (diff rsync_plan_test.expected rsync_plan_test.output)))

(executable
 (name rsync_test)
 (modules rsync_test)
 (libraries
  tsync_core
  tsync_store
  tsync_remote
  tsync_checkout
  tsync_sync
  unix))

(rule
 (with-stdout-to
  rsync_test.output
  (run ./rsync_test.exe)))

(rule
 (alias runtest)
 (action
  (diff rsync_test.expected rsync_test.output)))
