#!/usr/bin/env bash
# Emits the snapshot rules for every test directory, so a per-directory dune
# holds only its (executable ...) stanza and the convention lives in one place.
#
# A directory is a snapshot test when it has <exe>.expected, and a run-only test
# (exit status is the assertion) when it does not. Directories whose dune opens
# with (test ...) or (library ...) are left alone: dune's own test stanza already
# runs them, and a library is not a test.
#
# Run `dune build @gentests --auto-promote` after adding or renaming a test.
set -eu
cd "$(dirname "$0")"

# Byte order, not the machine's collation: this file is committed, and macOS and
# Linux disagree on where "_" sorts relative to "/".
export LC_ALL=C

# The only per-test variation worth a knob. Kept here rather than in each dune,
# so the exceptions are countable.
env_for() {
  case "$1" in
    content/cache_cap) echo "TSYNC_CHUNK_SIZE=8 TSYNC_MAX_CACHE=8" ;;
    content/demand_paging | content/fetch_range) echo "TSYNC_CHUNK_SIZE=8" ;;
    # The only test where a cache group holds more than one chunk, which is
    # what makes staging per group distinguishable from staging per chunk.
    scenario/staged_groups) echo "TSYNC_CHUNK_SIZE=8 TSYNC_CACHE_CHUNK_SIZE=24" ;;
    # These report timestamps in local time, which is what someone reading their
    # own server wants and what would otherwise make a snapshot depend on the
    # machine that recorded it.
    frontends/http_proxy | frontends/share_server | unit/zip) echo "TZ=UTC" ;;
    *) echo "" ;;
  esac
}

platform_for() {
  case "$1" in
    frontends/preview) echo "macosx" ;;
    *) echo "" ;;
  esac
}

# (setenv A 1 (setenv B 2 <inner>)), innermost first.
wrap_env() {
  local inner=$1 dir=$2 pair name value
  for pair in $(env_for "$dir"); do
    name=${pair%%=*}
    value=${pair#*=}
    inner="(setenv $name $value $inner)"
  done
  echo "$inner"
}

printf '; Generated by tests/gen-dune.sh -- do not edit.\n'
printf '; Run `dune build @gentests --auto-promote` after adding a test.\n'

# Tests are grouped by what they are for, so walk every level below the top.
for dune in $(find . -mindepth 2 -name dune | sed 's|^\./||' | sort); do
  dir=${dune%/dune}
  # Not hermetic: e2e mounts a real filesystem and starts a daemon, conformance
  # talks to real object stores with credentials only CI holds. Both are driven
  # by their own make target and deliberately stay out of `dune runtest`.
  case "$dir" in
    e2e/linux | e2e/macos | e2e/stress | conformance) continue ;;
  esac
  # First stanza keyword; comments and blank lines are skipped.
  kind=$(grep -m1 -oE '^\((executable|executables|test|tests|library)' "$dir/dune" | tr -d '(' || true)
  [ "$kind" = "executable" ] || continue
  exe=$(tr '\n' ' ' <"$dir/dune" | grep -oE '\(name [a-z_0-9]+\)' | head -1 | sed 's/(name //;s/)//')
  [ -n "$exe" ] || continue

  platform=$(platform_for "$dir")
  if [ -n "$platform" ]; then
    guard="
  (enabled_if
   (= %{system} $platform))"
  else
    guard=""
  fi

  printf '\n(subdir %s' "$dir"
  # A platform-gated test has no default-alias entry: dune would build the
  # executable on every platform to satisfy it.
  if [ -z "$platform" ]; then
    printf '\n (alias\n  (name default)\n  (deps %s.exe))' "$exe"
  fi

  if [ -f "$dir/$exe.expected" ]; then
    action=$(wrap_env "(run ./$exe.exe)" "$dir")
    printf '\n (rule\n  (alias runtest)%s\n  (target %s.output)\n  (action\n   (with-stdout-to %s.output (ignore-stderr %s))))' \
      "$guard" "$exe" "$exe" "$action"
    printf '\n (rule\n  (alias runtest)%s\n  (action\n   (diff %s.expected %s.output))))\n' \
      "$guard" "$exe" "$exe"
  else
    action=$(wrap_env "(run ./$exe.exe)" "$dir")
    printf '\n (rule\n  (alias runtest)%s\n  (action %s)))\n' "$guard" "$action"
  fi
done
