(library
 (flags
  (:standard
   -open
   Tsync_checkout
   -open
   Tsync_core
   -open
   Tsync_checkout_lwt
   -open
   Tsync_sync_lwt
   -open
   Tsync_remote_lwt
   -open
   Tsync_core_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_lwt
   -open
   Tsync_ipc_handler))
 (name tsync_engine)
 (public_name tsync-libs.engine)
 (libraries
  tsync_checkout
  unix
  lwt.unix
  yojson
  tsync_core
  tsync_checkout_lwt
  tsync_sync_lwt
  tsync_remote_lwt
  tsync_backend_lwt
  tsync_conf_lwt
  tsync_core_lwt
  tsync_ipc_handler
  lwt
  threads.posix))
