(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_checkout
   -open
   Tsync_checkout_lwt
   -open
   Tsync_cache_layout
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt))
 (name staged_codec_test)
 (libraries
  tsync_logical_key
  tsync_checkout
  tsync_checkout_lwt
  tsync_cache_layout
  tsync_conf_lwt
  tsync_backend_register
  tsync_backend_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix
  unix))
