; Manifest-level backend access on Lwt.

(library
 (flags
  (:standard -open Tsync_layout_lwt -open Tsync_conf_lwt -open Tsync_store -open Tsync_backend_lwt -open Tsync_io_lwt))
 (name tsync_store_lwt)
 (public_name tsync-libs.store_lwt)
 (libraries tsync_layout_lwt tsync_conf_lwt tsync_store tsync_backend_lwt tsync_io_lwt lwt))
