(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_remote_lwt
   -open
   Tsync_checkout_lwt
   -open
   Tsync_cache_layout_lwt
   -open
   Tsync_cache_layout
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_http_proxy_frontend
   -open
   Tsync_io_lwt))
 (name share_server_test)
 (libraries
  cohttp-lwt
  cohttp
  tsync_core
  tsync_remote_lwt
  tsync_checkout_lwt
  tsync_cache_layout_lwt
  tsync_cache_layout
  tsync_backend_register
  tsync_backend_lwt
  tsync_http_proxy_frontend
  tsync_io_lwt
  tsync-libs.core
  tsync_local_backend_lwt
  tsync_conf_lwt
  yojson
  lwt
  lwt.unix))
