(executable
 (flags
  (:standard
   -open
   Tsync_content
   -open
   Tsync_object
   -open
   Tsync_naming
   -open
   Tsync_conf
   -open
   Tsync_chunk
   -open
   Tsync_backend_register
   -open
   Tsync_local_backend
   -open
   Tsync_http_proxy_frontend))
 (name share_server_test)
 (libraries
  tsync_content
  tsync_object
  tsync_naming
  tsync_chunk
  tsync_backend_register
  tsync_http_proxy_frontend
  tsync_local_backend
  tsync_conf
  cohttp-lwt-unix
  yojson
  lwt
  lwt.unix))
