(executable
 (flags
  (:standard
   -open
   Tsync_remote
   -open
   Tsync_store
   -open
   Tsync_staged
   -open
   Tsync_checkout
   -open
   Tsync_content
   -open
   Tsync_naming
   -open
   Tsync_conf
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_local_backend
   -open
   Tsync_http_proxy_frontend
   -open
   Tsync_lwt_unix
   -open
   Tsync_metrics))
 (name share_server_test)
 (libraries
  tsync_remote
  tsync_store
  tsync_staged
  tsync_checkout
  tsync_content
  tsync_naming
  tsync_bigstring
  tsync_backend_register
  tsync_http_proxy_frontend
  tsync-libs.lwt_unix
  tsync-libs.metrics
  tsync_local_backend
  tsync_conf
  cohttp-lwt-unix
  yojson
  lwt
  lwt.unix))
