(executable
 (flags
  (:standard
   -open
   Tsync_checkout
   -open
   Tsync_logical_key
   -open
   Tsync_journal
   -open
   Tsync_sync
   -open
   Tsync_io_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend
   -open
   Tsync_test_harness))
 (name queue_bytes_test)
 (libraries
  tsync_checkout
  tsync_logical_key
  tsync_journal
  tsync_test_harness
  tsync_sync
  tsync_conf
  tsync_backend_register
  tsync_local_backend
  tsync_io_lwt
  lwt
  lwt.unix))
