(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_manifest
   -open
   Tsync_journal
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_remote
   -open
   Tsync_remote_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_test_harness))
 (name resync_test)
 (libraries
  tsync_core
  tsync_manifest
  tsync_journal
  tsync_test_harness
  tsync_ops
  tsync_ops_lwt
  tsync_remote
  tsync_remote_lwt
  tsync_conf_lwt
  tsync_backend_api
  tsync_backend_lwt
  tsync_local_backend_lwt
  tsync_cache_layout
  tsync_io
  unix
  lwt
  lwt.unix))
