(executable
 (flags
  (:standard
   -open
   Tsync_remote_lwt
   -open
   Tsync_layout_lwt
   -open
   Tsync_io_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_test_harness))
 (name chunk_pools)
 (libraries
  tsync_remote_lwt
  tsync_layout_lwt
  tsync_test_harness
  tsync_io_lwt
  tsync_conf_lwt
  tsync_local_backend_lwt))
