(executable
 (name chunk_cache_test)
 (libraries tsync_file tsync_conf tsync_backend tsync_queue lwt lwt.unix))

(alias
 (name default)
 (deps chunk_cache_test.exe))

(rule
 (alias runtest)
 (target chunk_cache_test.output)
 (action
  (with-stdout-to
   chunk_cache_test.output
   (ignore-stderr
    (run ./chunk_cache_test.exe)))))

(rule
 (alias runtest)
 (action
  (diff chunk_cache_test.expected chunk_cache_test.output)))
