(library
 (flags
  (:standard
   -open
   Tsync_field_spec
   -open
   Tsync_content
   -open
   Tsync_store
   -open
   Tsync_object
   -open
   Tsync_naming
   -open
   Tsync_ipc
   -open
   Tsync_log
   -open
   Tsync_metrics
   -open
   Tsync_zip
   -open
   Tsync_lwt_unix
   -open
   Tsync_http_proxy
   -open
   Tsync_chunk
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_frontend_register
   -open
   Tsync_diagnostics))
 (name tsync_http_proxy_frontend)
 (preprocess
  (pps ppx_blob))
 (preprocessor_deps
  %{project_root}/lambda/browse.html
  %{project_root}/lambda/player.js
  %{project_root}/lambda/mime.json
  stats.html)
 (libraries
  tsync-libs.field_spec
  tsync-libs.content
  tsync-libs.store
  tsync-libs.object
  tsync-libs.naming
  tsync-libs.lwt_unix
  tsync-libs.frontend_register
  tsync-libs.http_proxy
  tsync-libs.ipc
  tsync-libs.diagnostics
  tsync-libs.metrics
  tsync-libs.chunk
  tsync-libs.backend_register
  tsync-libs.conf
  tsync-libs.zip
  tsync-libs.log
  cohttp-lwt-unix
  bigstringaf
  conduit-lwt-unix
  uri
  yojson
  lwt
  lwt.unix))
