(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_manifest
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_remote
   -open
   Tsync_remote_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_domain_store_lwt
   -open
   Tsync_io_lwt
   -open
   Tsync_test_harness))
 (name gc_cost)
 (libraries
  tsync-libs.core
  tsync_manifest
  tsync_core
  tsync_test_harness
  tsync_ops
  tsync_ops_lwt
  tsync_remote
  tsync_remote_lwt
  tsync_conf_lwt
  tsync_backend_register
  tsync_backend_lwt
  tsync_local_backend_lwt
  tsync_io_lwt
  tsync_domain_store_lwt
  lwt
  lwt.unix))
