(executable
 (flags
  (:standard
   -open
   Tsync_ops
   -open
   Tsync_store
   -open
   Tsync_object
   -open
   Tsync_naming
   -open
   Tsync_chunk
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend
   -open
   Tsync_domain_store
   -open
   Tsync_local_io))
 (name gc_cost)
 (libraries
  tsync_ops
  tsync_store
  tsync_object
  tsync_naming
  tsync_conf
  tsync_chunk
  tsync_backend_register
  tsync_local_backend
  tsync_local_io
  tsync_domain_store
  lwt
  lwt.unix
  unix))
