(library
 (flags
  (:standard
   -open
   Tsync_retry
   -open
   Tsync_metrics
   -open
   Tsync_log
   -open
   Tsync_local_io
   -open
   Tsync_io_lwt))
 (name tsync_work)
 (public_name tsync-libs.work)
 (libraries
  tsync_retry
  tsync_metrics
  tsync_local_io
  tsync_log
  tsync_io_lwt
  lwt
  lwt.unix
  unix))
