(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_checkout
   -open
   Tsync_manifest
   -open
   Tsync_field_spec
   -open
   Tsync_sync
   -open
   Tsync_naming
   -open
   Tsync_ipc
   -open
   Tsync_metrics
   -open
   Tsync_lwt_unix
   -open
   Tsync_local_io
   -open
   Tsync_conf
   -open
   Tsync_ipc_handler
   -open
   Tsync_engine
   -open
   Tsync_frontend_register
   -open
   Tsync_log))
 (name tsync_fuse_frontend)
 (private_modules fuse_fs hidden_ops internal_ops path_ops)
 (optional)
 (libraries
  tsync_logical_key
  tsync_checkout
  tsync_manifest
  tsync-libs.field_spec
  tsync-libs.sync
  tsync-libs.naming
  tsync-libs.frontend_register
  tsync-libs.log
  tsync-libs.conf
  tsync-libs.engine
  tsync-libs.ipc
  tsync-libs.metrics
  tsync-libs.local_io
  tsync-libs.ipc_handler
  tsync-libs.lwt_unix
  fuse3
  unix
  lwt
  lwt.unix
  threads.posix))
