(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_metrics
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_domain_store
   -open
   Tsync_test_harness))
 (name backend_traffic)
 (libraries
  tsync-libs.logical_key
  tsync_test_harness
  tsync_metrics
  tsync_bigstring
  tsync_backend_register
  tsync_backend_lwt
  tsync_local_backend_lwt
  tsync_domain_store
  lwt
  lwt.unix
  unix))
