(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_journal
   -open
   Tsync_remote_lwt
   -open
   Tsync_io_lwt
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_http_proxy_backend_lwt
   -open
   Tsync_frontend_register
   -open
   Tsync_diagnostics
   -open
   Tsync_frontend
   -open
   Tsync_http_proxy_frontend
   -open
   Tsync_test_harness))
 (name proxy_watch)
 (libraries
  cohttp-lwt
  unix
  tsync-libs.core
  tsync_core
  tsync_journal
  tsync_test_harness
  tsync_remote_lwt
  tsync_http_proxy_frontend
  tsync_backend_api
  tsync_backend_lwt
  tsync_local_backend_lwt
  tsync_http_proxy_backend_lwt
  tsync_frontend_register
  tsync_frontend
  tsync_diagnostics
  tsync_conf_lwt
  tsync_io_lwt
  cohttp
  yojson
  lwt
  lwt.unix
  uri))
