services:
  dev:
    build:
      context: ../..
      dockerfile: linux/docker/Dockerfile
    volumes:
      - ../..:/workspace
    environment:
      - TSYNC_CONFIG_JSON
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true
    tty: true
