(library
 (flags
  (:standard
   -open
   Tsync_field_spec
   -open
   Tsync_log
   -open
   Tsync_backend_register
   -open
   Tsync_http_client))
 (name tsync_gcs_backend)
 (private_modules gcs_auth)
 (library_flags (-linkall))
 (libraries
  tsync_field_spec
  tsync_backend_register
  tsync_log
  tsync_http_client
  cohttp-lwt-unix
  uri
  yojson
  base64
  x509
  mirage-crypto-pk
  lwt
  lwt.unix))
