(library
 (flags
  (:standard
   -open
   Tsync_retry
   -open
   Tsync_chunk_integrity
   -open
   Tsync_field_spec
   -open
   Tsync_log
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_http_client))
 (name tsync_gcs_backend)
 (private_modules gcs_auth)
 (library_flags (-linkall))
 (libraries
  tsync_retry
  tsync_chunk_integrity
  tsync-libs.field_spec
  tsync-libs.bigstring
  tsync-libs.backend_register
  tsync_http_client
  tsync-libs.log
  cohttp-lwt-unix
  uri
  yojson
  base64
  x509
  mirage-crypto-pk
  lwt
  lwt.unix))
