(library
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_chunk_integrity
   -open
   Tsync_backend_register
   -open
   Tsync_io))
 (name tsync_gcs_backend)
 (private_modules gcs_auth)
 (libraries
  cohttp
  tsync-libs.core
  tsync_core
  tsync_io
  tsync_chunk_integrity
  tsync-libs.backend_register
  uri
  yojson
  base64
  x509
  mirage-crypto-pk))
