(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_staged
   -open
   Tsync_checkout
   -open
   Tsync_file_ops
   -open
   Tsync_sync
   -open
   Tsync_store
   -open
   Tsync_log
   -open
   Tsync_conf
   -open
   Tsync_backend_register
   -open
   Tsync_ipc_handler
   -open
   Tsync_durable_queue_lwt))
 (name tsync_engine)
 (public_name tsync-libs.engine)
 (libraries
  unix
  lwt.unix
  yojson
  tsync_logical_key
  tsync_staged
  tsync_checkout
  tsync_file_ops
  tsync_sync
  tsync_store
  tsync_backend_register
  tsync_conf
  tsync_ipc_handler
  tsync_log
  tsync_durable_queue_lwt
  lwt
  threads.posix))
