(executable
 (flags
  (:standard
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_test_harness))
 (name import_listing)
 (libraries
  tsync_test_harness
  tsync_ops
  tsync_ops_lwt
  tsync_conf_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix
  unix))
