(executable
 (flags
  (:standard
   -open
   Tsync_wal
   -open
   Tsync_wal_lwt
   -open
   Tsync_journal
   -open
   Tsync_sync_lwt
   -open
   Tsync_file_lwt
   -open
   Tsync_io_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_test_harness))
 (name pause_test)
 (libraries
  tsync_wal
  tsync_wal_lwt
  tsync_journal
  tsync_test_harness
  tsync_sync_lwt
  tsync_file_lwt
  tsync_conf_lwt
  tsync_local_backend_lwt
  tsync_io_lwt
  lwt
  lwt.unix))
