(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_chunks
   -open
   Tsync_checkout
   -open
   Tsync_bigstring
   -open
   Tsync_naming
   -open
   Tsync_conf
   -open
   Tsync_backend_register
   -open
   Tsync_domain_store
   -open
   Tsync_local_backend
   -open
   Tsync_ops
   -open
   Tsync_test_harness))
 (name mirror_probe)
 (libraries
  tsync-libs.logical_key
  tsync_chunks
  tsync_checkout
  tsync_test_harness
  tsync_bigstring
  tsync_naming
  tsync_conf
  tsync_backend_register
  tsync_domain_store
  tsync_local_backend
  tsync_ops
  lwt
  lwt.unix
  unix))
