(library
 (flags
  (:standard
   -open
   Tsync_object
   -open
   Tsync_conf
   -open
   Tsync_engine
   -open
   Tsync_ipc
   -open
   Tsync_frontend_register
   -open
   Tsync_log))
 (name tsync_headless_frontend)
 (library_flags (-linkall))
 (libraries
  tsync_object
  tsync_conf
  tsync_engine
  tsync_ipc
  tsync_frontend_register
  tsync_log
  lwt
  lwt.unix))
