(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_journal
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_remote_lwt
   -open
   Tsync_checkout_lwt
   -open
   Tsync_sync_lwt
   -open
   Tsync_test_harness))
 (name cursor_watch)
 (libraries
  tsync-libs.core
  tsync_journal
  tsync_test_harness
  tsync_conf_lwt
  tsync_core
  tsync_backend_register
  tsync_backend_lwt
  tsync_remote_lwt
  tsync_checkout_lwt
  tsync_sync_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix
  unix))
