; The Google store on Lwt, and where it registers itself.

(library
 (flags
  (:standard
   -open
   Tsync_gcs_backend
   -open
   Tsync_backend_lwt
   -open
   Tsync_http_client_lwt
   -open
   Tsync_io_lwt))
 (name tsync_gcs_backend_lwt)
 (library_flags (-linkall))
 (libraries
  tsync_gcs_backend
  tsync_backend_lwt
  tsync_http_client_lwt
  tsync_io_lwt
  cohttp
  cohttp-lwt
  cohttp-lwt-unix
  uri
  unix
  lwt))
