(executable
 (flags
  (:standard
   -open
   Tsync_checkout_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_test_harness))
 (name wal_log_test)
 (libraries
  tsync_checkout_lwt
  tsync_conf_lwt
  tsync_test_harness
  tsync_backend_lwt
  tsync_local_backend_lwt))
