(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_test_harness))
 (name get_range)
 (libraries
  tsync-libs.core
  tsync_test_harness
  tsync_core
  tsync_backend_api
  tsync_backend_lwt
  tsync_local_backend_lwt
  bigstringaf
  lwt
  lwt.unix))
