(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_remote_lwt
   -open
   Tsync_checkout_lwt
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt))
 (name promote_race)
 (libraries
  unix
  tsync_core
  tsync_remote_lwt
  tsync_checkout_lwt
  tsync_conf_lwt
  tsync_backend_api
  tsync_backend_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix))
