(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_remote
   -open
   Tsync_staged
   -open
   Tsync_checkout
   -open
   Tsync_content
   -open
   Tsync_naming
   -open
   Tsync_metrics
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend))
 (name promote_race)
 (libraries
  tsync_logical_key
  tsync_remote
  tsync_staged
  tsync_checkout
  tsync_content
  tsync_naming
  tsync_conf
  tsync_backend_register
  tsync_local_backend
  tsync_metrics
  lwt
  lwt.unix))
