(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_remote_lwt
   -open
   Tsync_staged_lwt
   -open
   Tsync_content_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt))
 (name promote_race)
 (libraries
  unix
  tsync_logical_key
  tsync_remote_lwt
  tsync_staged_lwt
  tsync_content_lwt
  tsync_conf_lwt
  tsync_backend_register
  tsync_backend_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix))
