(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_manifests_lwt
   -open
   Tsync_manifest
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_test_harness))
 (name manifests_memo_test)
 (libraries
  tsync_logical_key
  tsync_manifests_lwt
  tsync_manifest
  tsync_test_harness
  tsync_conf_lwt
  tsync_backend_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix
  unix))
