(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_history
   -open
   Tsync_staged
   -open
   Tsync_checkout
   -open
   Tsync_manifest
   -open
   Tsync_journal
   -open
   Tsync_chunks
   -open
   Tsync_test_harness
   -open
   Tsync_ops
   -open
   Tsync_store
   -open
   Tsync_sync
   -open
   Tsync_naming
   -open
   Tsync_conf_parsing
   -open
   Tsync_local_io
   -open
   Tsync_io_lwt
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_domain_store
   -open
   Tsync_local_backend
   -open
   Tsync_diagnostics
   -open
   Tsync_ipc_handler))
 (name tsync_test_runner)
 (libraries
  tsync_logical_key
  tsync_history
  tsync_staged
  tsync_checkout
  tsync_manifest
  tsync_journal
  tsync_chunks
  tsync_test_harness
  tsync_ops
  tsync_store
  tsync_sync
  tsync_naming
  tsync_io_lwt
  tsync_local_io
  tsync_conf
  tsync_bigstring
  tsync_backend_register
  tsync_domain_store
  tsync_local_backend
  tsync_conf_parsing
  tsync_ipc_handler
  tsync_diagnostics
  yojson
  unix
  lwt
  lwt.unix
  threads.posix))
