(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_history
   -open
   Tsync_staged
   -open
   Tsync_staged_lwt
   -open
   Tsync_checkout
   -open
   Tsync_file_lwt
   -open
   Tsync_wal
   -open
   Tsync_wal_lwt
   -open
   Tsync_manifest
   -open
   Tsync_journal
   -open
   Tsync_chunks
   -open
   Tsync_test_harness
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_layout_lwt
   -open
   Tsync_file_store_lwt
   -open
   Tsync_corruption
   -open
   Tsync_corruption_lwt
   -open
   Tsync_sync_lwt
   -open
   Tsync_folder_ids_lwt
   -open
   Tsync_cache_layout
   -open
   Tsync_cache_layout_lwt
   -open
   Tsync_conf_parsing
   -open
   Tsync_io_lwt
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf
   -open
   Tsync_conf_lwt
   -open
   Tsync_domain_store_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_diagnostics
   -open
   Tsync_ipc_handler))
 (name tsync_test_runner)
 (libraries
  tsync_logical_key
  tsync_history
  tsync_staged
  tsync_staged_lwt
  tsync_checkout
  tsync_file_lwt
  tsync_wal
  tsync_wal_lwt
  tsync_manifest
  tsync_journal
  tsync_chunks
  tsync_test_harness
  tsync_ops
  tsync_ops_lwt
  tsync_layout_lwt
  tsync_file_store_lwt
  tsync_corruption
  tsync_corruption_lwt
  tsync_sync_lwt
  tsync_folder_ids_lwt
  tsync_cache_layout
  tsync_cache_layout_lwt
  tsync_io_lwt
  tsync_conf
  tsync_conf_lwt
  tsync_bigstring
  tsync_backend_register
  tsync_backend_lwt
  tsync_domain_store_lwt
  tsync_local_backend_lwt
  tsync_conf_parsing
  tsync_ipc_handler
  tsync_diagnostics
  yojson
  unix
  lwt
  lwt.unix))
