(library
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_remote
   -open
   Tsync_checkout
   -open
   Tsync_checkout_lwt
   -open
   Tsync_manifest
   -open
   Tsync_journal
   -open
   Tsync_test_harness
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_remote_lwt
   -open
   Tsync_sync_lwt
   -open
   Tsync_cache_layout_lwt
   -open
   Tsync_cache_layout
   -open
   Tsync_conf_parsing
   -open
   Tsync_io_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf
   -open
   Tsync_conf_lwt
   -open
   Tsync_domain_store_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_diagnostics
   -open
   Tsync_ipc_handler))
 (name tsync_test_runner)
 (libraries
  tsync_core
  tsync_remote
  tsync_checkout
  tsync_checkout_lwt
  tsync_manifest
  tsync_journal
  tsync_test_harness
  tsync_ops
  tsync_ops_lwt
  tsync_remote_lwt
  tsync_sync_lwt
  tsync_cache_layout_lwt
  tsync_cache_layout
  tsync_io_lwt
  tsync_conf
  tsync_conf_lwt
  tsync_backend_register
  tsync_backend_lwt
  tsync_domain_store_lwt
  tsync_local_backend_lwt
  tsync_conf_parsing
  tsync_ipc_handler
  tsync_diagnostics
  yojson
  unix
  lwt
  lwt.unix))
