(executable
 (flags
  (:standard
   -open
   Tsync_checkout
   -open
   Tsync_manifest
   -open
   Tsync_chunks
   -open
   Tsync_naming
   -open
   Tsync_conf
   -open
   Tsync_backend_register
   -open
   Tsync_local_backend
   -open
   Tsync_local_io
   -open
   Tsync_test_harness))
 (name manifest_memo_test)
 (libraries
  tsync_checkout
  tsync_manifest
  tsync_chunks
  tsync_test_harness
  tsync_naming
  tsync_conf
  tsync_backend_register
  tsync_local_backend
  tsync_local_io
  lwt
  lwt.unix
  unix))
