(executable
 (name lane)
 (libraries
  tsync_lane_backend
  tsync_local_backend
  tsync_local_io
  tsync_file
  lwt
  lwt.unix
  unix))

(alias
 (name default)
 (deps lane.exe))

(rule
 (alias runtest)
 (target lane.output)
 (action
  (with-stdout-to
   lane.output
   (ignore-stderr
    (run ./lane.exe)))))

(rule
 (alias runtest)
 (action
  (diff lane.expected lane.output)))
