opam-version: "2.0"
synopsis: "Android frontend for tsync, driven by directed commands"
maintainer: ["Romain Beauxis <toots@rastageeks.org>"]
authors: ["Romain Beauxis <toots@rastageeks.org>"]
license: "MIT"
homepage: "https://github.com/toots/tsync"
bug-reports: "https://github.com/toots/tsync/issues"
depends: [
  "ocaml" {>= "5.1"}
  "dune" {>= "3.23"}
  "tsync-libs" {= version}
  "yojson"
  "lwt"
  "odoc" {with-doc}
]
build: [
  ["dune" "subst"] {dev}
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
    "@doc" {with-doc}
  ]
]
x-maintenance-intent: ["(latest)"]
