(executable
 (name preview_test)
 (enabled_if
  (= %{system} macosx))
 (libraries tsync_file_provider lwt lwt.unix unix))

(rule
 (alias runtest)
 (enabled_if
  (= %{system} macosx))
 (target preview_test.output)
 (action
  (with-stdout-to
   preview_test.output
   (ignore-stderr
    (run ./preview_test.exe)))))

(rule
 (alias runtest)
 (enabled_if
  (= %{system} macosx))
 (action
  (diff preview_test.expected preview_test.output)))
