(library
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_io
   -open
   Tsync_chunk_integrity
   -open
   Tsync_backend_register
   -open
   Tsync_device))
 (name tsync_local_backend)
 (libraries
  tsync-libs.core
  tsync_core
  tsync_io
  tsync_chunk_integrity
  tsync-libs.backend_register
  tsync_device
  unix))
