(library
 (flags
  (:standard
   -open
   Tsync_field_spec
   -open
   Tsync_lwt_unix
   -open
   Tsync_local_io
   -open
   Tsync_chunk
   -open
   Tsync_backend_register
   -open
   Tsync_naming
   -open
   Tsync_log
   -open
   Tsync_device))
 (name tsync_local_backend)
 (library_flags (-linkall))
 (libraries
  tsync_field_spec
  tsync_chunk
  tsync_backend_register
  tsync_naming
  tsync_log
  tsync_device
  tsync_local_io
  tsync_lwt_unix
  unix
  lwt
  lwt.unix))
