(library
 (flags
  (:standard
   -open
   Tsync_filename
   -open
   Tsync_chunk_integrity
   -open
   Tsync_chunks
   -open
   Tsync_field_spec
   -open
   Tsync_lwt_unix
   -open
   Tsync_local_io
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_log
   -open
   Tsync_device))
 (name tsync_local_backend)
 (library_flags (-linkall))
 (libraries
  tsync_filename
  tsync_chunk_integrity
  tsync_chunks
  tsync-libs.field_spec
  tsync-libs.bigstring
  tsync-libs.backend_register
  tsync-libs.log
  tsync_device
  tsync-libs.local_io
  tsync-libs.lwt_unix
  unix
  lwt
  lwt.unix))
