(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_remote
   -open
   Tsync_remote_lwt
   -open
   Tsync_manifest
   -open
   Tsync_test_harness
   -open
   Tsync_content
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt))
 (name known_chunks)
 (libraries
  unix
  lwt.unix
  lwt
  tsync_logical_key
  tsync_remote
  tsync_remote_lwt
  tsync_manifest
  tsync_test_harness
  tsync_content
  tsync_conf
  tsync_conf_lwt
  tsync_backend_register
  tsync_backend_lwt
  tsync_local_backend_lwt))
