; The shared journal and the local mark on it, on Lwt.

(library
 (flags
  (:standard
   -open
   Tsync_file_store
   -open
   Tsync_conf_lwt
   -open
   Tsync_layout_lwt
   -open
   Tsync_store_lwt
   -open
   Tsync_journal
   -open
   Tsync_bigstring
   -open
   Tsync_io_lwt))
 (name tsync_file_store_lwt)
 (public_name tsync-libs.file_store_lwt)
 (libraries
  tsync_file_store
  tsync_conf_lwt
  tsync_layout_lwt
  tsync_store_lwt
  tsync_journal
  tsync_bigstring
  tsync_io_lwt
  lwt))
