(executable
 (flags
  (:standard
   -open
   Tsync_content
   -open
   Tsync_object
   -open
   Tsync_naming
   -open
   Tsync_metrics
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend))
 (name staged_test)
 (libraries
  tsync_content
  tsync_object
  tsync_naming
  tsync_conf
  tsync_backend_register
  tsync_local_backend
  tsync_metrics
  lwt
  lwt.unix))

(alias
 (name default)
 (deps staged_test.exe))

(rule
 (alias runtest)
 (target staged_test.output)
 (action
  (with-stdout-to
   staged_test.output
   (ignore-stderr
    (run ./staged_test.exe)))))

(rule
 (alias runtest)
 (action
  (diff staged_test.expected staged_test.output)))
