(executable
 (name staged_test)
 (libraries
  tsync_file
  tsync_conf
  tsync_backend
  tsync_local_backend
  tsync_queue
  tsync_metrics
  lwt
  lwt.unix))

(alias
 (name default)
 (deps staged_test.exe))

(rule
 (alias runtest)
 (target staged_test.output)
 (action
  (with-stdout-to
   staged_test.output
   (ignore-stderr
    (run ./staged_test.exe)))))

(rule
 (alias runtest)
 (action
  (diff staged_test.expected staged_test.output)))
