(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_remote
   -open
   Tsync_manifest
   -open
   Tsync_chunks
   -open
   Tsync_content
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend
   -open
   Tsync_test_harness))
 (name staged_fanout_test)
 (libraries
  tsync_logical_key
  tsync_remote
  tsync_manifest
  tsync_chunks
  tsync_test_harness
  tsync_content
  tsync_conf
  tsync_backend_register
  tsync_local_backend
  lwt
  lwt.unix
  unix))
