(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_checkout
   -open
   Tsync_sync
   -open
   Tsync_manifest
   -open
   Tsync_journal
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_remote_lwt
   -open
   Tsync_cache_layout_lwt
   -open
   Tsync_log
   -open
   Tsync_metrics
   -open
   Tsync_io_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_register
   -open
   Tsync_diagnostics))
 (name tsync_ipc_handler)
 (public_name tsync-libs.ipc_handler)
 (libraries
  tsync_logical_key
  tsync_checkout
  tsync_sync
  tsync_manifest
  tsync_journal
  tsync_ops
  tsync_ops_lwt
  tsync_remote_lwt
  tsync_cache_layout_lwt
  tsync_backend_register
  tsync_io_lwt
  tsync_conf_lwt
  tsync_metrics
  tsync_diagnostics
  tsync_log
  yojson
  unix
  lwt))
