(library
 (flags
  (:standard
   -open
   Tsync_naming
   -open
   Tsync_log
   -open
   Tsync_lwt_unix
   -open
   Tsync_local_io
   -open
   Tsync_chunk
   -open
   Tsync_backend_register
   -open
   Tsync_work))
 (name tsync_domain_store)
 (libraries
  tsync_naming
  tsync_work
  tsync_chunk
  tsync_backend_register
  tsync_local_io
  tsync_lwt_unix
  tsync_log
  lwt
  unix
  lwt.unix
  yojson))
