(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_manifest
   -open
   Tsync_checkout_lwt
   -open
   Tsync_checkout
   -open
   Tsync_cache_layout
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_test_harness))
 (name chunk_cache_test)
 (libraries
  unix
  tsync-libs.core
  tsync_manifest
  tsync_checkout_lwt
  tsync_checkout
  tsync_test_harness
  tsync_cache_layout
  tsync_core
  tsync_conf_lwt
  tsync_backend_api
  tsync_backend_lwt
  lwt
  lwt.unix))
