(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_manifest
   -open
   Tsync_staged_lwt
   -open
   Tsync_chunk_cache
   -open
   Tsync_checkout_maintenance_lwt
   -open
   Tsync_chunk_cache_lwt
   -open
   Tsync_cache_layout
   -open
   Tsync_xxhash
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_test_harness))
 (name chunk_cache_test)
 (libraries
  unix
  tsync-libs.logical_key
  tsync_manifest
  tsync_staged_lwt
  tsync_chunk_cache
  tsync_checkout_maintenance_lwt
  tsync_chunk_cache_lwt
  tsync_test_harness
  tsync_cache_layout
  tsync_xxhash
  tsync_conf_lwt
  tsync_bigstring
  tsync_backend_register
  tsync_backend_lwt
  lwt
  lwt.unix))
