(executable
 (flags
  (:standard
   -open
   Tsync_manifest
   -open
   Tsync_staged
   -open
   Tsync_chunk_cache
   -open
   Tsync_chunks
   -open
   Tsync_content
   -open
   Tsync_naming
   -open
   Tsync_xxhash
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_test_harness))
 (name chunk_cache_test)
 (libraries
  tsync_manifest
  tsync_staged
  tsync_chunk_cache
  tsync_chunks
  tsync_test_harness
  tsync_content
  tsync_naming
  tsync_xxhash
  tsync_conf
  tsync_bigstring
  tsync_backend_register
  lwt
  lwt.unix))
