(executable
 (flags
  (:standard
   -open
   Tsync_sync
   -open
   Tsync_object
   -open
   Tsync_local_io
   -open
   Tsync_backend_register
   -open
   Tsync_conf
   -open
   Tsync_local_backend))
 (name queue_bytes_test)
 (libraries
  tsync_sync
  tsync_object
  tsync_conf
  tsync_backend_register
  tsync_local_backend
  tsync_local_io
  lwt
  lwt.unix))

(alias
 (name default)
 (deps queue_bytes_test.exe))

(rule
 (alias runtest)
 (target queue_bytes_test.output)
 (action
  (with-stdout-to
   queue_bytes_test.output
   (ignore-stderr
    (run ./queue_bytes_test.exe)))))

(rule
 (alias runtest)
 (action
  (diff queue_bytes_test.expected queue_bytes_test.output)))
