(library
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_staged
   -open
   Tsync_checkout
   -open
   Tsync_manifest
   -open
   Tsync_journal
   -open
   Tsync_ops
   -open
   Tsync_sync
   -open
   Tsync_store
   -open
   Tsync_naming
   -open
   Tsync_ipc
   -open
   Tsync_log
   -open
   Tsync_metrics
   -open
   Tsync_io_lwt
   -open
   Tsync_local_io
   -open
   Tsync_conf
   -open
   Tsync_backend_register
   -open
   Tsync_diagnostics))
 (name tsync_ipc_handler)
 (public_name tsync-libs.ipc_handler)
 (libraries
  tsync_logical_key
  tsync_staged
  tsync_checkout
  tsync_manifest
  tsync_journal
  tsync_ops
  tsync_sync
  tsync_store
  tsync_naming
  tsync_backend_register
  tsync_local_io
  tsync_conf
  tsync_ipc
  tsync_metrics
  tsync_diagnostics
  tsync_log
  tsync_io_lwt
  yojson
  unix
  lwt
  lwt.unix))
