(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_chunk_integrity
   -open
   Tsync_chunks
   -open
   Tsync_journal
   -open
   Tsync_io_lwt))
 (name layout)
 (libraries
  tsync-libs.logical_key
  tsync_chunk_integrity
  tsync_chunks
  tsync_journal
  tsync_io_lwt
  unix))
