(executable
 (name backfill)
 (libraries
  tsync_backfill_backend
  tsync_local_backend
  tsync_file
  lwt
  lwt.unix
  unix))

(alias
 (name default)
 (deps backfill.exe))

(rule
 (alias runtest)
 (target backfill.output)
 (action
  (with-stdout-to
   backfill.output
   (ignore-stderr
    (run ./backfill.exe)))))

(rule
 (alias runtest)
 (action
  (diff backfill.expected backfill.output)))
