(test
 (flags
  (:standard
   -open
   Tsync_chunk
   -open
   Tsync_backend_register
   -open
   Tsync_content
   -open
   Tsync_object
   -open
   Tsync_conf
   -open
   Tsync_test_harness))
 (name fetch_fanout_test)
 (libraries
  tsync_test_harness
  tsync_chunk
  tsync_backend_register
  tsync_content
  tsync_object
  tsync_conf
  lwt
  lwt.unix
  unix))
