(test
 (flags
  (:standard
   -open
   Tsync_chunk_cache
   -open
   Tsync_chunks
   -open
   Tsync_bigstring
   -open
   Tsync_backend_register
   -open
   Tsync_content
   -open
   Tsync_conf
   -open
   Tsync_test_harness))
 (name fetch_fanout_test)
 (libraries
  tsync_chunk_cache
  tsync_chunks
  tsync_test_harness
  tsync_bigstring
  tsync_backend_register
  tsync_content
  tsync_conf
  lwt
  lwt.unix
  unix))
