(library
 (flags
  (:standard
   -open
   Tsync_frontend_register
   -open
   Tsync_engine
   -open
   Tsync_conf
   -open
   Tsync_log
   -open
   Tsync_lwt_unix))
 (name tsync_launcher)
 (public_name tsync-libs.launcher)
 (libraries
  tsync_frontend_register
  tsync-libs.engine
  tsync-libs.conf
  tsync-libs.log
  tsync-libs.lwt_unix))
