(executable
 (flags
  (:standard
   -open
   Tsync_journal
   -open
   Tsync_ops
   -open
   Tsync_conf
   -open
   Tsync_file_store
   -open
   Tsync_test_harness))
 (name import_batching)
 (libraries
  tsync_journal
  tsync_test_harness
  tsync_ops
  tsync_conf
  tsync_file_store
  tsync_local_backend
  lwt
  lwt.unix
  unix))
