(library
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_http_proxy
   -open
   Tsync_backend_register
   -open
   Tsync_io))
 (name tsync_http_proxy_backend)
 (libraries
  cohttp
  tsync-libs.core
  tsync_core
  tsync_io
  tsync-libs.backend_register
  tsync-libs.http_proxy
  uri
  yojson))
