(executable
 (name codec_test)
 (modules codec_test)
 (libraries tsync_core tsync_remote))

(rule
 (with-stdout-to
  codec_test.output
  (run ./codec_test.exe)))

(rule
 (alias runtest)
 (action
  (diff codec_test.expected codec_test.output)))

(executable
 (name remote_test)
 (modules remote_test)
 (libraries tsync_core tsync_store tsync_remote unix))

(rule
 (with-stdout-to
  remote_test.output
  (run ./remote_test.exe)))

(rule
 (alias runtest)
 (action
  (diff remote_test.expected remote_test.output)))

(executable
 (name index_test)
 (modules index_test)
 (libraries tsync_core tsync_store tsync_remote unix))

(rule
 (with-stdout-to
  index_test.output
  (run ./index_test.exe)))

(rule
 (alias runtest)
 (action
  (diff index_test.expected index_test.output)))
