(library
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_checkout
   -open
   Tsync_checkout_lwt
   -open
   Tsync_manifest
   -open
   Tsync_conf_lwt
   -open
   Tsync_engine
   -open
   Tsync_diagnostics
   -open
   Tsync_frontend_register))
 (name tsync_android_frontend)
 (public_name tsync-android)
 (libraries
  bigstringaf
  tsync_core
  tsync_checkout
  tsync_conf_lwt
  tsync-libs.checkout_lwt
  tsync_manifest
  tsync-libs.engine
  tsync-libs.diagnostics
  tsync-libs.frontend_register
  tsync-libs.core
  yojson
  lwt
  lwt.unix))
