(library
 (flags
  (:standard
   -open
   Tsync_stdlib
   -open
   Tsync_core
   -open
   Tsync_checkout
   -open
   Tsync_cache_layout
   -open
   Tsync_core_lwt
   -open
   Tsync_io_lwt
   -open
   Tsync_conf
   -open
   Tsync_conf_lwt
   -open
   Tsync_engine
   -open
   Tsync_frontend_register))
 (name tsync_fuse_frontend)
 (private_modules fuse_fs hidden_ops internal_ops path_ops)
 (optional)
 (libraries
  tsync_stdlib
  tsync_core
  tsync_cache_layout
  tsync_conf_lwt
  tsync_checkout
  tsync-libs.core
  tsync-libs.frontend_register
  tsync-libs.conf
  tsync-libs.engine
  tsync-libs.core_lwt
  tsync_io_lwt
  fuse3
  unix
  lwt
  lwt.unix))
