(executable
 (name fetch_range)
 (libraries tsync_test_runner))

(alias
 (name default)
 (deps fetch_range.exe))

(rule
 (alias runtest)
 (target fetch_range.output)
 (action
  (with-stdout-to
   fetch_range.output
   (ignore-stderr
    (setenv
     TSYNC_CHUNK_SIZE
     8
     (run ./fetch_range.exe))))))

(rule
 (alias runtest)
 (action
  (diff fetch_range.expected fetch_range.output)))
