(executable
 (flags
  (:standard
   -open
   Tsync_filename
   -open
   Tsync_bigstring
   -open
   Tsync_bigstring_lwt
   -open
   Tsync_xxhash
   -open
   Tsync_test_harness
   -open
   Tsync_device))
 (name bigstring_test)
 (libraries
  tsync_filename
  tsync_test_harness
  unix
  lwt.unix
  bigstringaf
  tsync_bigstring
  tsync_bigstring_lwt
  tsync_xxhash
  tsync-libs.device))
