(executable
 (flags
  (:standard
   -open
   Tsync_io
   -open
   Tsync_core
   -open
   Tsync_io_lwt
   -open
   Tsync_test_harness
   -open
   Tsync_device))
 (name bigstring_test)
 (libraries
  tsync_io
  tsync_test_harness
  unix
  lwt.unix
  bigstringaf
  tsync_core
  tsync_io_lwt
  tsync-libs.device))
