(library
 (flags
  (:standard
   -open
   Tsync_checkout
   -open
   Tsync_manifest
   -open
   Tsync_conf
   -open
   Tsync_sync
   -open
   Tsync_engine
   -open
   Tsync_ipc_handler
   -open
   Tsync_diagnostics
   -open
   Tsync_frontend_register
   -open
   Tsync_log))
 (name tsync_android_frontend)
 (public_name tsync-android)
 (libraries
  tsync_checkout
  tsync_manifest
  tsync-libs.conf
  tsync-libs.sync
  tsync-libs.engine
  tsync-libs.ipc_handler
  tsync-libs.diagnostics
  tsync-libs.frontend_register
  tsync-libs.log
  yojson
  lwt
  lwt.unix))
