(* Which names the mirror keeps for itself.

   The mirror hides its scratch files from listings and deletes them on startup.
   Both of those are destructive when the test for "ours" is wider than the
   names we actually create: a user's file is then invisible and then gone.

   That happened. The test was the ".tmp" suffix alone, which is every file
   Syncthing has in flight -- it names them ".syncthing.<name>.tmp". A folder
   pointed at the mount downloaded the same twelve gigabytes continuously and
   landed nothing, because each start swept the partial files away and no
   listing ever admitted they existed.

   So what is pinned here is mostly the negative: the names that must survive.
   A recogniser that is too narrow leaves scratch files lying around, which
   costs disk. One that is too wide eats user data. *)

let case name = Printf.printf "\n=== %s\n" name

let show name =
  Printf.printf "  %-34s %s\n" name
    (if Fs_util.is_temp_name name then "ours" else "user's")

let () =
  case "the names we generate";
  (* Taken from [temp_path] rather than written out, so a change to the naming
     scheme shows up here instead of silently making the recogniser miss.
     Classified before the pid is masked, so what is tested is the real name. *)
  let pid = string_of_int (Unix.getpid ()) in
  let mask name =
    let n = String.length name and m = String.length pid in
    let rec go i =
      if i + m > n then name
      else if String.sub name i m = pid then
        String.sub name 0 i ^ "<pid>" ^ String.sub name (i + m) (n - i - m)
      else go (i + 1)
    in
    go 0
  in
  List.iter
    (fun p ->
      let name = Filename.basename (Fs_util.temp_path p) in
      Printf.printf "  %-34s %s\n" (mask name)
        (if Fs_util.is_temp_name name then "ours" else "user's"))
    ["/a/b/file.txt"; "/a/b/other.mkv"];

  case "files a user might have";
  List.iter show
    [
      (* The one that was eaten. *)
      ".syncthing.Big.Buck.Bunny.mkv.tmp";
      "download.part.tmp";
      "no.dot.lead.mkv.tmp";
      "x.tmp";
      ".tmp";
      "plain.txt";
      ".dot.txt";
      ".hidden";
    ];

  case "near misses";
  (* Our prefix without our suffix, and our suffix without our prefix: both are
     someone else's file. A name has to have been generated by [temp_path] to
     count, and that means both ends. *)
  List.iter show
    [
      ".tsync-tmp-123-4.tmp";
      ".tsync-tmp-123-4.txt";
      ".tsync-tmp-";
      "tsync-tmp-123-4.tmp";
      "my.tsync-tmp-1-2.tmp";
    ]
