(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_checkout
   -open
   Tsync_checkout_lwt
   -open
   Tsync_cache_layout
   -open
   Tsync_conf_lwt
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_io_lwt
   -open
   Tsync_remote
   -open
   Tsync_remote_lwt
   -open
   Tsync_ops
   -open
   Tsync_ops_lwt
   -open
   Tsync_manifest
   -open
   Tsync_test_harness))
 (name integrity_tree_test)
 (libraries
  tsync_core
  tsync_checkout
  tsync_checkout_lwt
  tsync_cache_layout
  tsync_test_harness
  tsync_conf_lwt
  tsync_backend_api
  tsync_backend_lwt
  tsync_local_backend_lwt
  tsync_io_lwt
  tsync_remote
  tsync_remote_lwt
  tsync_ops
  tsync_ops_lwt
  tsync_manifest
  str
  lwt
  lwt.unix))
