(library
 (flags
  (:standard
   -open
   Tsync_sync
   -open
   Tsync_store
   -open
   Tsync_naming
   -open
   Tsync_ipc
   -open
   Tsync_metrics
   -open
   Tsync_lwt_unix
   -open
   Tsync_local_io
   -open
   Tsync_conf
   -open
   Tsync_ipc_handler
   -open
   Tsync_engine
   -open
   Tsync_backend_register
   -open
   Tsync_log))
 (name tsync_fuse)
 (private_modules hidden_ops internal_ops path_ops)
 (optional)
 (libraries
  tsync_sync
  tsync_store
  tsync_naming
  tsync_backend_register
  tsync_log
  tsync_conf
  tsync_engine
  tsync_ipc
  tsync_metrics
  tsync_local_io
  tsync_ipc_handler
  tsync_lwt_unix
  fuse3
  lwt
  lwt.unix
  threads.posix))
