(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_manifest
   -open
   Tsync_backend_lwt
   -open
   Tsync_local_backend_lwt
   -open
   Tsync_domain_store
   -open
   Tsync_domain_store_lwt
   -open
   Tsync_test_harness))
 (name backfill)
 (libraries
  tsync-libs.core
  tsync_manifest
  tsync_core
  tsync_test_harness
  tsync_backend_lwt
  tsync_domain_store
  tsync_domain_store_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix))
