(library
 (flags
  (:standard
   -open
   Tsync_checkout
   -open
   Tsync_checkout_lwt
   -open
   Tsync_core
   -open
   Tsync_remote_lwt
   -open
   Tsync_journal
   -open
   Tsync_remote
   -open
   Tsync_cache_layout
   -open
   Tsync_core_lwt
   -open
   Tsync_io_lwt
   -open
   Tsync_backend_api
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf
   -open
   Tsync_conf_lwt
   -open
   Tsync_conf_parsing))
 (name tsync_diagnostics)
 (public_name tsync-libs.diagnostics)
 (libraries
  tsync_checkout
  tsync_checkout_lwt
  tsync-libs.conf_parsing
  tsync_core
  tsync_remote_lwt
  tsync_journal
  tsync_remote
  tsync_cache_layout
  tsync_io
  tsync_io_lwt
  tsync_conf
  tsync_conf_lwt
  tsync_backend_api
  tsync_backend_lwt
  tsync_core_lwt
  yojson
  unix
  lwt
  lwt.unix))
