(library
 (name contract)
 (modules contract)
 (libraries tsync_core tsync_store unix))

(executable
 (name local_test)
 (modules local_test)
 (libraries contract tsync_core tsync_store unix yojson))

(rule
 (with-stdout-to local_test.output (run ./local_test.exe)))

(rule
 (alias runtest)
 (action (diff local_test.expected local_test.output)))
