(library
 (flags
  (:standard
   -open
   Tsync_frontend_register
   -open
   Tsync_conf_parsing
   -open
   Tsync_domain
   -open
   Tsync_engine
   -open
   Tsync_conf
   -open
   Tsync_log
   -open
   Tsync_lwt_unix
   -open
   Tsync_ipc
   -open
   Tsync_runtime
   -open
   Tsync_ipc_handler
   -open
   Tsync_diagnostics))
 (name tsync_launcher)
 (libraries
  tsync_frontend_register
  tsync-libs.conf_parsing
  tsync_domain
  tsync-libs.engine
  tsync-libs.conf
  tsync-libs.log
  tsync-libs.lwt_unix
  tsync-libs.ipc
  tsync-libs.ipc_handler
  tsync-libs.diagnostics
  tsync_runtime
  yojson
  lwt))
