(executable
 (flags
  (:standard
   -open
   Tsync_core
   -open
   Tsync_manifest
   -open
   Tsync_remote_lwt
   -open
   Tsync_checkout
   -open
   Tsync_checkout_lwt
   -open
   Tsync_conf
   -open
   Tsync_test_harness
   -open
   Tsync_remote
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt))
 (name partial_local)
 (libraries
  tsync_core
  tsync_manifest
  tsync_remote_lwt
  tsync_checkout
  tsync_checkout_lwt
  tsync_conf
  tsync_test_harness
  tsync_remote
  tsync_conf_lwt
  tsync_backend_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix))
