(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_manifest
   -open
   Tsync_remote_lwt
   -open
   Tsync_checkout
   -open
   Tsync_checkout_lwt
   -open
   Tsync_manifests_lwt
   -open
   Tsync_conf
   -open
   Tsync_test_harness
   -open
   Tsync_content_lwt
   -open
   Tsync_store
   -open
   Tsync_bigstring
   -open
   Tsync_backend_lwt
   -open
   Tsync_conf_lwt
   -open
   Tsync_local_backend_lwt))
 (name partial_local)
 (libraries
  tsync_logical_key
  tsync_manifest
  tsync_remote_lwt
  tsync_checkout
  tsync_checkout_lwt
  tsync_manifests_lwt
  tsync_conf
  tsync_test_harness
  tsync_content_lwt
  tsync_store
  tsync_bigstring
  tsync_conf_lwt
  tsync_backend_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix))
