(executable
 (flags
  (:standard
   -open
   Tsync_logical_key
   -open
   Tsync_chunks
   -open
   Tsync_bigstring
   -open
   Tsync_backend_lwt
   -open
   Tsync_domain_store
   -open
   Tsync_domain_store_lwt
   -open
   Tsync_local_backend_lwt))
 (name deferred_shards)
 (libraries
  tsync-libs.logical_key
  tsync_chunks
  tsync_bigstring
  tsync_backend_lwt
  tsync_domain_store
  tsync_domain_store_lwt
  tsync_local_backend_lwt
  lwt
  lwt.unix
  unix))
